name: Build kubernetes cluster

on:
  push:
    branches:
      - master
    tags:
      - 'Blutgang-*'

jobs:

  ci-core:
    name: ci-core
    runs-on: ubuntu-latest

    steps:

    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Context for Buildx
      shell: bash
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: makemake1337/blutgang
        tags: |
          type=semver,pattern=Blutgang-{{version}}
          type=semver,pattern=Blutgang-{{version}},value=latest
          type=ref,event=branch
          type=ref,event=pr

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: docker-build-push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        platforms: linux/amd64,linux/arm64

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}


  kube-ci: 
    name: kube-ci
    runs-on: debian-latest
    needs: ci-core
    steps:

    - name: install deps
      run: |
        curl -fLO https://github.com/stern/stern/releases/download/v1.28.0/stern_1.28.0_linux_amd64.tar.gz
        tar xzf stern_1.28.0_linux_amd64.tar.gz
        chmod +x stern
        sudo mv stern /usr/local/bin/stern
    - name: start cluster
      run: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.27.10+k3s1 K3S_KUBECONFIG_MODE=777 sh -s - --docker
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    - name: debug
      run: |
        kubectl get nodes
        echo "------------------------ DESCRIBE ON PODS ------------------------"
        kubectl describe pods
